/* eslint-disable react-refresh/only-export-components */
import NavBar from "../components/NavBar";
import ShoppingCart from '../components/cartComponents/ShoppingCart'
import HomePage from "../pages/HomePage";
export const routes = () => {
    return [
        { path: "/", name: "home", ele: <HomePage /> },
        { path: "/test", name: "test", ele: <NavBar /> },
        { path: "/Cart", ele: <ShoppingCart /> },
    ];
}
export const sections = () => {
    return [
        {
            sectionName: "Men clothes",
            path: "/MenSection",
            cardData: [
                {
                    img: "https://picsum.photos/200/300",
                    title: "1x",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw3dGFlE6Q1yNpdFrF5JedCA6mNqY83QtA2lLoS3wBePxIi2OF_elLKvj2FCyGpdTSKBc&usqp=CAU",
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw3dGFlE6Q1yNpdFrF5JedCA6mNqY83QtA2lLoS3wBePxIi2OF_elLKvj2FCyGpdTSKBc&usqp=CAU",
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw3dGFlE6Q1yNpdFrF5JedCA6mNqY83QtA2lLoS3wBePxIi2OF_elLKvj2FCyGpdTSKBc&usqp=CAU",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "x2",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "3",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "4",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "5",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "6",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "7",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "8",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
            ],
        },
        {
            sectionName: "Women's Clothing",
            path: "/WomenSection",
            cardData: [
                {
                    img: "https://picsum.photos/200/300",
                    title: "9",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "10",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "11",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "12",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "13",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "14",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "15",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "16",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
            ],
        },
        {
            sectionName: "Baby girls clothes",
            path: "/girlsSection",
            cardData: [
                {
                    img: "https://picsum.photos/200/300",
                    title: "17",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "18",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "19",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "20",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "21",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "22",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "23",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "24",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
            ],
        },
        {
            sectionName: "Baby boys clothes",
            path: "/boysSection",
            cardData: [
                {
                    img: "https://picsum.photos/200/300",
                    title: "25",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "26",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "27",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "30",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "31",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "32",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "33",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
                {
                    img: "https://picsum.photos/200/300",
                    title: "34",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                        "https://picsum.photos/200/300",
                    ]
                },
            ],
        },
    ]
};
export const CartProducts = (state = [], action = { type: "" }) => {
    if (action.type !== "") {
        state.splice(+action.type, 1)
    }
    if (action.ProductData) {
        state.push(action.ProductData)
        // if (!state.some(item => item.title === action.ProductData.title)) {
        //     state.push(action.ProductData)
        // } else {
        //     state.findIndex(products => console.log(products.title))
        // }
    }
    return state
}
export const SearchData = (state = [], action = { type: "" }) => {
    // console.log(action)
    return state
}

