/* eslint-disable react-refresh/only-export-components */
import moment from "moment";
import SearchPage from "../components/SearchPage/SearchPage";
import ShoppingCart from '../components/cartComponents/ShoppingCart'
import BestSellerPage from "../pages/BestSellerPage";
import HomePage from "../pages/HomePage";
import NewMerchandise from "../pages/NewMerchandise";
import SalePage from "../pages/SalePage";
import BuyPage from "../pages/BuyPage";
export const routes = () => {
    return [
        { path: "/electronic-shop", name: "home", ele: <HomePage /> },
        { path: "/Sale", name: "Sale", ele: <SalePage /> },
        { path: "/Best-Seller", name: "Best Seller", ele: <BestSellerPage /> },
        { path: "/New-Merchandise", name: "New merchandise", ele: <NewMerchandise /> },
        { path: "/SearchPage", ele: <SearchPage /> },
        { path: "/Cart", ele: <ShoppingCart /> },
        { path: "/buy", ele: <BuyPage /> },
    ];
}
const day = moment().format("DD")
const month = moment().format("MM")
const year = moment().format("YYYY")
export const MainData = () => {
    return [
        {
            sectionName: "Men clothes",
            path: "/MenSection",
            cardData: [
                {
                    discount: 10,
                    BestSeller: true,
                    Date: `${month - 1}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=16",
                    title: "Silk Elegance",
                    price: "120",
                    text: `Turn heads with this elegant silk dress. Perfect for special occasions, the dress features a flattering silhouette and intricate detailing, making it a must-have for your wardrobe.`,
                    moreDetails: [
                        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw3dGFlE6Q1yNpdFrF5JedCA6mNqY83QtA2lLoS3wBePxIi2OF_elLKvj2FCyGpdTSKBc&usqp=CAU",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/201/301",
                        "https://picsum.photos/202/302",
                        "https://picsum.photos/203/303",
                        "https://picsum.photos/204/304",
                        "https://picsum.photos/205/305",
                        "https://picsum.photos/206/306",
                        "https://picsum.photos/207/307",
                        "https://picsum.photos/208/308",
                        "https://picsum.photos/209/309",
                        "https://picsum.photos/210/310",
                    ]
                },
                {
                    discount: 15,
                    BestSeller: false,
                    Date: `${month - 1}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=17",
                    title: "Denim Classic",
                    price: "45",
                    text: `Stay comfortable and stylish with our casual denim jeans. The jeans are made from high-quality denim and are designed for a relaxed fit, making them a versatile addition to your everyday wardrobe.`,
                    moreDetails: [
                        "https://picsum.photos/220/320",
                        "https://picsum.photos/221/321",
                        "https://picsum.photos/222/322",
                        "https://picsum.photos/223/323",
                        "https://picsum.photos/224/324",
                        "https://picsum.photos/225/325",
                        "https://picsum.photos/226/326",
                        "https://picsum.photos/227/327",
                        "https://picsum.photos/228/328",
                        "https://picsum.photos/229/329",
                        "https://picsum.photos/230/330",
                        "https://picsum.photos/231/331",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=10",
                    title: "Leather Chic",
                    price: "80",
                    text: `Step out in style with these chic leather ankle boots. The boots feature a trendy design with comfortable heels, making them perfect for both casual and formal occasions.`,
                    moreDetails: [
                        "https://picsum.photos/240/340",
                        "https://picsum.photos/241/341",
                        "https://picsum.photos/242/342",
                        "https://picsum.photos/243/343",
                        "https://picsum.photos/244/344",
                        "https://picsum.photos/245/345",
                        "https://picsum.photos/246/346",
                        "https://picsum.photos/247/347",
                        "https://picsum.photos/248/348",
                        "https://picsum.photos/249/349",
                        "https://picsum.photos/250/350",
                        "https://picsum.photos/251/351",
                    ]
                },
                {
                    discount: 5,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=45",
                    title: "Knit Comfort",
                    price: "35",
                    text: `Stay warm and stylish with our cozy knit sweater. The sweater is made`,
                    moreDetails: [
                        "https://picsum.photos/260/360",
                        "https://picsum.photos/261/361",
                        "https://picsum.photos/262/362",
                        "https://picsum.photos/263/363",
                        "https://picsum.photos/264/364",
                        "https://picsum.photos/265/365",
                        "https://picsum.photos/266/366",
                        "https://picsum.photos/267/367",
                        "https://picsum.photos/268/368",
                        "https://picsum.photos/269/369",
                        "https://picsum.photos/270/370",
                        "https://picsum.photos/271/371",
                    ]
                },
                {
                    discount: 8,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "Classic Aviator",
                    price: "25",
                    text: `Add a touch of style to your outfit with our classic aviator sunglasses. The sunglasses feature a timeless design and provide UV protection, making them both fashionable and functional.`,
                    moreDetails: [
                        "https://picsum.photos/280/380",
                        "https://picsum.photos/281/381",
                        "https://picsum.photos/282/382",
                        "https://picsum.photos/283/383",
                        "https://picsum.photos/284/384",
                        "https://picsum.photos/285/385",
                        "https://picsum.photos/286/386",
                        "https://picsum.photos/287/387",
                        "https://picsum.photos/288/388",
                        "https://picsum.photos/289/389",
                        "https://picsum.photos/290/390",
                        "https://picsum.photos/291/391",
                    ]
                },
                {
                    discount: 20,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "Smart Fitness",
                    price: "70",
                    text: `Stay fit and connected with our smart fitness tracker. The tracker features advanced fitness metrics, heart rate monitoring, and smartphone integration, making it the perfect companion for your active lifestyle.`,
                    moreDetails: [
                        "https://picsum.photos/300/400",
                        "https://picsum.photos/301/401",
                        "https://picsum.photos/302/402",
                        "https://picsum.photos/303/403",
                        "https://picsum.photos/304/404",
                        "https://picsum.photos/305/405",
                        "https://picsum.photos/306/406",
                        "https://picsum.photos/307/407",
                        "https://picsum.photos/308/408",
                        "https://picsum.photos/309/409",
                        "https://picsum.photos/310/410",
                        "https://picsum.photos/311/411",
                    ]
                },
                {
                    discount: 12,
                    BestSeller: true,
                    Date: `${month - 1}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "Cozy Blanket",
                    price: "50",
                    text: `Snuggle up with our cozy blanket. Made from soft and warm fabric, this blanket is perfect for chilly nights. Its stylish design also adds a touch of elegance to your home.`,
                    moreDetails: [
                        "https://picsum.photos/320/420",
                        "https://picsum.photos/321/421",
                        "https://picsum.photos/322/422",
                        "https://picsum.photos/323/423",
                        "https://picsum.photos/324/424",
                        "https://picsum.photos/325/425",
                        "https://picsum.photos/326/426",
                        "https://picsum.photos/327/427",
                        "https://picsum.photos/328/428",
                        "https://picsum.photos/329/429",
                        "https://picsum.photos/330/430",
                        "https://picsum.photos/331/431",
                    ]
                },
                {
                    discount: 18,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "Modern Desk Lamp",
                    price: "40",
                    text: `Illuminate your workspace with our modern desk lamp. The lamp features adjustable brightness and color temperature, providing the perfect lighting for any task. Its sleek design adds a touch of sophistication to your desk.`,
                    moreDetails: [
                        "https://picsum.photos/340/440",
                        "https://picsum.photos/341/441",
                        "https://picsum.photos/342/442",
                        "https://picsum.photos/343/443",
                        "https://picsum.photos/344/444",
                        "https://picsum.photos/345/445",
                        "https://picsum.photos/346/446",
                        "https://picsum.photos/347/447",
                        "https://picsum.photos/348/448",
                        "https://picsum.photos/349/449",
                        "https://picsum.photos/350/450",
                        "https://picsum.photos/351/451",
                    ]
                },
            ],
        },
        {
            sectionName: "Women's Clothing",
            path: "/WomenSection",
            cardData: [
                {
                    discount: 5,
                    BestSeller: true,
                    Date: `${month - 1}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=1",
                    title: "Awesome Watch",
                    price: "99.99",
                    text: `High-quality watch with a modern design. Suitable for any occasion.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3?random=11",
                        "https://picsum.photos/200/300?random=3?random=12",
                        "https://picsum.photos/200/300?random=3?random=13",
                    ],
                },
                {
                    discount: 15,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=2",
                    title: "Gaming Mouse",
                    price: "49.99",
                    text: `Advanced gaming mouse with customizable buttons and RGB lighting.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3?random=21",
                        "https://picsum.photos/200/300?random=3?random=22",
                        "https://picsum.photos/200/300?random=3?random=23",
                    ],
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=3",
                    title: "Wireless Headphones",
                    price: "79.99",
                    text: `Immersive sound experience with wireless convenience. Comfortable for long listening sessions.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3?random=31",
                        "https://picsum.photos/200/300?random=3?random=32",
                        "https://picsum.photos/200/300?random=3?random=33",
                    ],
                },
                {
                    discount: 20,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=4",
                    title: "Smartphone Holder",
                    price: "19.99",
                    text: `Universal smartphone holder for your car. Keep your phone secure while driving.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3?random=41",
                        "https://picsum.photos/200/300?random=3?random=42",
                        "https://picsum.photos/200/300?random=3?random=43",
                    ],
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=5",
                    title: "Fitness Tracker",
                    price: "69.99",
                    text: `Monitor your daily activities and stay fit with this advanced fitness tracker.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3?random=51",
                        "https://picsum.photos/200/300?random=3?random=52",
                        "https://picsum.photos/200/300?random=3?random=53",
                    ],
                },
                {
                    discount: 10,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=6",
                    title: "Coffee Maker",
                    price: "89.99",
                    text: `Start your day with the perfect cup of coffee. Easy to use and clean.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3?random=61",
                        "https://picsum.photos/200/300?random=3?random=62",
                        "https://picsum.photos/200/300?random=3?random=63",
                    ],
                },
                {
                    discount: false,
                    BestSeller: true,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=7",
                    title: "Bluetooth Speaker",
                    price: "39.99",
                    text: `Portable Bluetooth speaker with high-quality sound. Perfect for outdoor activities.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3?random=71",
                        "https://picsum.photos/200/300?random=3?random=72",
                        "https://picsum.photos/200/300?random=3?random=73",
                    ],
                },
                {
                    discount: false,
                    BestSeller: true,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3?random=8",
                    title: "Power Bank",
                    price: "29.99",
                    text: `Never run out of battery. Portable power bank for your electronic devices.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3?random=81",
                        "https://picsum.photos/200/300?random=3?random=82",
                        "https://picsum.photos/200/300?random=3?random=83",
                    ],
                },
            ],
        },
        {
            sectionName: "Baby girls clothes",
            path: "/girlsSection",
            cardData: [
                {
                    discount: false,
                    BestSeller: true,
                    Date: `${month - 1}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=09",
                    title: "17",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=345",
                    title: "18",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3789",
                    title: "19",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "20",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "21",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "22",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "23",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "24",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
            ],
        },
        {
            sectionName: "Baby boys clothes",
            path: "/boysSection",
            cardData: [
                {
                    discount: false,
                    BestSeller: true,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=9",
                    title: "25",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=37",
                    title: "26",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=66",
                    title: "27",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=35",
                    title: "30",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=380",
                    title: "31",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "32",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "33",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
                {
                    discount: false,
                    BestSeller: false,
                    Date: `${month}/${day}/${year}`,
                    count: 1,
                    img: "https://picsum.photos/200/300?random=3",
                    title: "34",
                    price: "23.5",
                    text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
                    moreDetails: [
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                        "https://picsum.photos/200/300?random=3",
                    ]
                },
            ],
        },
    ]
};
export const CartProducts = (state = [], action = { type: "", DeleteIndex: "" }) => {
    if (action.type !== "") {
        if (state.length > 0) {
            if (state[+action.type].count > 1) {
                state[+action.type].count = state[+action.type].count - 1
            } else {
                state.splice(+action.type, 1)
            }
        }
    }
    if (action.ProductData) {
        if (!state.some(item => item.title === action.ProductData.title)) {
            state.push(action.ProductData)
        } else if (state.some(item => item.title === action.ProductData.title)) {
            const index = state.findIndex(products => products.title === action.ProductData.title)
            state[index].count = state[index].count + 1
        }
    }
    return state
}







